"""Basketball POSTED LOTS recap — every lot/single actually pushed live to eBay
so far from the Spurs-through-Rockets posting run (2026-07-22, two rounds).
Pulls collage images already generated by _post_basketball_spurs_heat.py and
_post_basketball_nuggets_rockets.py. Writes docs/basketball_posted_lots.pdf
(+ ~/Downloads).
"""
import shutil
from pathlib import Path
from PIL import Image as PILImage
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

GRAY_DK = colors.HexColor("#222222")
GRAY_MD = colors.HexColor("#555555")
GRAY_LT = colors.HexColor("#e8e8e8")
BLACK = colors.black
WHITE = colors.white

# (key, collage_dir, title, price, card_count, item_id)
ROUND1 = [
 ("spurs1","/tmp/bball_collages","2025-26 Topps Spurs 5 Card Lot Sochan x2 Barnes Castle Paul",8.49,5,"307078580329"),
 ("spurs2","/tmp/bball_collages","2025-26 Topps Steve Kerr Spurs Legend Basketball",2.99,1,"307078580364"),
 ("clippers","/tmp/bball_collages","2025-26 Topps Clippers 4 Card Lot Powell x3 Jones Jr",7.49,4,"307078580413"),
 ("pistons1","/tmp/bball_collages","2025-26 Topps Pistons 5 Card Lot Cunningham Thomas Ivey Basketball",8.99,5,"307078580462"),
 ("pistons2","/tmp/bball_collages","2025-26 Topps Pistons 2 Card Lot Ivey Duren Basketball",4.49,2,"307078580491"),
 ("nets","/tmp/bball_collages","2025-26 Topps Nic Claxton Nets Basketball",2.49,1,"307078580521"),
 ("celtics","/tmp/bball_collages","2025-26 Topps Kristaps Porzingis Celtics Basketball",2.99,1,"307078580571"),
 ("bulls1","/tmp/bball_collages","2025-26 Topps Bulls 5 Card Lot White x3 Giddey Ball Basketball",8.49,5,"307078580612"),
 ("bulls2","/tmp/bball_collages","2025-26 Topps Patrick Williams Bulls Basketball",2.99,1,"307078580641"),
 ("thunder","/tmp/bball_collages","2025-26 Topps Thunder 5 Card Lot Hartenstein Wiggins Holmgren Joe",8.99,5,"307078580698"),
 ("wizards","/tmp/bball_collages","2025-26 Topps Wizards 4 Card Lot Coulibaly Holmes Sarr Basketball",7.49,4,"307078580740"),
 ("magic","/tmp/bball_collages","2025-26 Topps Magic 3 Card Lot Black x2 Banchero Basketball",6.49,3,"307078580782"),
 ("blazers","/tmp/bball_collages","2025-26 Topps Deni Avdija Trail Blazers Basketball",2.99,1,"307078580819"),
 ("cavaliers","/tmp/bball_collages","2025-26 Topps Cavaliers 3 Card Lot Mobley Garland Jerome",6.49,3,"307078580857"),
 ("pelicans","/tmp/bball_collages","2025-26 Topps Pelicans 3 Card Lot Missi Jones Murphy Chrome",6.49,3,"307078580910"),
 ("timberwolves","/tmp/bball_collages","2025-26 Topps Timberwolves 4 Card Lot Reid x3 Garnett Legend",7.49,4,"307078580958"),
 ("pacers1","/tmp/bball_collages","2025-26 Topps Pacers 5 Card Lot McConnell Mathurin Nembhard",8.99,5,"307078581013"),
 ("pacers2","/tmp/bball_collages","2025-26 Topps Obi Toppin Pacers Basketball",2.99,1,"307078581102"),
 ("hornets","/tmp/bball_collages","2025-26 Topps Hornets 3 Card Lot LaMelo Ball x2 Salaun",6.49,3,"307078581166"),
 ("warriors","/tmp/bball_collages","2025-26 Topps Warriors 2 Card Lot Post Kuminga Basketball",4.49,2,"307078581223"),
 ("grizzlies","/tmp/bball_collages","2025-26 Topps Grizzlies 4 Card Lot Bane x3 Jackson Jr Basketball",7.49,4,"307078581288"),
 ("heat","/tmp/bball_collages","2025-26 Topps Heat 4 Card Lot Herro Jaquez Jr x2 Adebayo",7.49,4,"307078581345"),
]
ROUND2 = [
 ("nuggets","/tmp/bball_collages2","2025-26 Topps Nuggets 5 Card Lot Murray Braun Watson x2 Basketball",8.99,5,"307078654306"),
 ("suns","/tmp/bball_collages2","2025-26 Topps Suns 4 Card Lot Ighodaro x3 Allen Basketball",7.49,4,"307078654375"),
 ("mavericks","/tmp/bball_collages2","2025-26 Topps Mavericks 4 Card Lot Irving Washington Christie Basketball",7.99,4,"307078654435"),
 ("raptors","/tmp/bball_collages2","2025-26 Topps Raptors 5 Card Lot Agbaji x2 Quickley x2 Dick Basketball",8.99,5,"307078654531"),
 ("kings","/tmp/bball_collages2","2025-26 Topps Kings 2 Card Lot Monk LaVine Chrome Basketball",4.99,2,"307078654615"),
 ("hawks","/tmp/bball_collages2","2025-26 Topps Hawks 3 Card Lot Webb Johnson Chrome Capela Basketball",6.49,3,"307078654723"),
 ("rockets","/tmp/bball_collages2","2025-26 Topps Rockets 2 Card Lot VanVleet Chrome Smith Jr Basketball",4.49,2,"307078654787"),
]

st=getSampleStyleSheet()
h1=ParagraphStyle("h1",parent=st["Title"],fontSize=21,spaceAfter=2,textColor=BLACK)
sub=ParagraphStyle("sub",parent=st["Normal"],fontSize=9.5,textColor=GRAY_MD,spaceAfter=10)
grp=ParagraphStyle("grp",parent=st["Heading2"],fontSize=13,textColor=BLACK,spaceBefore=14,spaceAfter=6)
note=ParagraphStyle("note",parent=st["Normal"],fontSize=8.5,textColor=GRAY_MD,spaceBefore=8)
cardp=ParagraphStyle("cardp",parent=st["Normal"],fontSize=9.5,leading=12,textColor=BLACK)
linkp=ParagraphStyle("linkp",parent=st["Normal"],fontSize=8,leading=10,textColor=colors.HexColor("#0645AD"))

def money(x): return f"${x:,.2f}" if x%1 else f"${int(x)}"

out = Path("docs/basketball_posted_lots.pdf")
doc = SimpleDocTemplate(str(out), pagesize=letter, topMargin=.55*inch, bottomMargin=.55*inch,
                         leftMargin=.6*inch, rightMargin=.6*inch)

total_cards = sum(r[4] for r in ROUND1+ROUND2)
total_price = round(sum(r[3] for r in ROUND1+ROUND2), 2)
total_lots = len(ROUND1) + len(ROUND2)

flow = [
 Paragraph("Basketball &mdash; POSTED LOTS", h1),
 Paragraph(f"{total_lots} lots/singles &middot; {total_cards} cards &middot; {money(total_price)} combined list price "
           f"&middot; all LIVE on eBay as of 2026-07-22", sub),
 Paragraph(f"<b>Round 1 (Spurs&ndash;Heat, 18 teams):</b> {len(ROUND1)} lots, {sum(r[4] for r in ROUND1)} cards, "
           f"{money(round(sum(r[3] for r in ROUND1),2))}. <b>Round 2 (Nuggets&ndash;Rockets, 7 teams):</b> "
           f"{len(ROUND2)} lots, {sum(r[4] for r in ROUND2)} cards, {money(round(sum(r[3] for r in ROUND2),2))}. "
           "Round 2 corrections: Fred VanVleet (Rockets) and Jalen Johnson (Hawks) were both relabeled base "
           "when they're actually Topps Chrome &mdash; fixed before posting. Immanuel Quickley (Raptors) posted "
           "as 2 copies, not the 3 the sheet claimed &mdash; only 2 could be found across every scan. Kevin "
           "Durant's extra Rockets \"base\" card was held back entirely &mdash; no 3rd physical copy could be "
           "located; still open on the sell sheet for JC to track down.", note),
]

def section(title, rows):
    flow.append(Paragraph(title, grp))
    for key, cdir, ltitle, price, n, item_id in rows:
        img_path = Path(cdir) / f"{key}.jpg"
        iw, ih = PILImage.open(img_path).size
        max_w, max_h = 2.6*inch, 1.3*inch
        scale = min(max_w/iw, max_h/ih)
        disp_w, disp_h = iw*scale, ih*scale
        row_data = [[
            RLImage(str(img_path), width=disp_w, height=disp_h),
            Paragraph(f"<b>{ltitle}</b><br/>{n} card{'s' if n!=1 else ''} &middot; {money(price)}<br/>"
                      f"Item {item_id}", cardp),
        ]]
        t = Table(row_data, colWidths=[2.7*inch, 4.1*inch])
        t.setStyle(TableStyle([
            ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("GRID",(0,0),(-1,-1),.3,GRAY_MD),
            ("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),
            ("LEFTPADDING",(0,0),(-1,-1),8),
        ]))
        flow.append(t)
        flow.append(Spacer(1, 6))

section(f"Round 1 &mdash; Spurs through Heat ({len(ROUND1)} lots)", ROUND1)
section(f"Round 2 &mdash; Nuggets through Rockets ({len(ROUND2)} lots)", ROUND2)

doc.build(flow)
dl = Path.home()/"Downloads"/out.name
shutil.copy(out, dl)
print(f"{total_lots} lots, {total_cards} cards, {money(total_price)} total -> {out} -> {dl}")
