terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0"
    }
  }
}

# ---------------------------------------------------------------------------
# Provider — uses existing 'pokemon-app' SSO profile
# ---------------------------------------------------------------------------
provider "aws" {
  region  = var.aws_region
  profile = "pokemon-app"

  default_tags {
    tags = {
      username   = "jason.chletsos@fivetran.com"
      expires_on = "2027-01-01"
      department = "sales"
      team       = "sales_engineering"
      project    = "ebay-fivetran-connector"
      managed_by = "terraform"
    }
  }
}

# ---------------------------------------------------------------------------
# Variables
# ---------------------------------------------------------------------------
variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "ebay_verification_token" {
  description = "Secret token registered in eBay Developer Portal for endpoint verification"
  type        = string
  sensitive   = true
}

# ebay_endpoint_url is set to the API Gateway URL after first apply
# On first apply leave blank — the deploy script handles the two-step automatically
variable "ebay_endpoint_url" {
  description = "Full HTTPS URL of this endpoint — populated automatically by deploy.sh"
  type        = string
  default     = ""
}

variable "ebay_client_id" {
  description = "eBay App ID / Client ID (Production keyset)"
  type        = string
  default     = "JasonChl-jasonchl-PRD-d8f6186d5-ea3d812b"
}

variable "ebay_client_secret" {
  description = "eBay Cert ID / Client Secret (Production keyset)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "ebay_refresh_token" {
  description = "eBay OAuth refresh token for Trading API calls"
  type        = string
  sensitive   = true
  default     = ""
}

variable "ebay_dev_id" {
  description = "eBay Dev ID"
  type        = string
  default     = "218c1bd6-f212-4d17-b1fb-fb07fa4f0c94"
}

variable "ebay_ru_name" {
  description = "RuName generated by eBay after adding the Redirect URL"
  type        = string
  default     = ""
}

# ---------------------------------------------------------------------------
# Reddit posting (optional). Leave blank to disable Reddit cross-post.
# Setup:
#   1. Create app at https://www.reddit.com/prefs/apps (type: "script")
#   2. Copy the client ID (under the app name) and secret
#   3. Get a refresh token via the OAuth flow (one-time)
#   4. Set TF_VAR_reddit_client_id, TF_VAR_reddit_client_secret, TF_VAR_reddit_refresh_token
# ---------------------------------------------------------------------------
variable "reddit_client_id" {
  description = "Reddit script app client ID"
  type        = string
  sensitive   = true
  default     = ""
}

variable "reddit_client_secret" {
  description = "Reddit script app client secret"
  type        = string
  sensitive   = true
  default     = ""
}

variable "reddit_refresh_token" {
  description = "Reddit OAuth refresh token (long-lived)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "reddit_user_agent" {
  description = "User-Agent string for Reddit API (required, must be unique)"
  type        = string
  default     = "harpua2001-crosspost/1.0 by harpua2001"
}

# ---------------------------------------------------------------------------
# Fivetran — Refresh button triggers the eBay→warehouse sync alongside the
# GitHub Pages rebuild. Connector ID is the managed eBay connector at Fivetran.
# ---------------------------------------------------------------------------
variable "fivetran_api_key" {
  description = "Fivetran API key (account-level key)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "fivetran_api_secret" {
  description = "Fivetran API secret"
  type        = string
  sensitive   = true
  default     = ""
}

variable "fivetran_connector_id" {
  description = "ID of the eBay Fivetran connector to sync on refresh"
  type        = string
  default     = "sentient_ragweed"
}

# ---------------------------------------------------------------------------
# Admin-login alerting — email-sent SNS topic
# ---------------------------------------------------------------------------
variable "admin_alert_email" {
  description = "Email to receive admin-login alerts"
  type        = string
  default     = "jchletsos@gmail.com"
}

variable "admin_known_devices" {
  description = "Comma-separated UUIDs of devices that should NOT trigger an alert"
  type        = string
  default     = ""
}

variable "admin_known_ip_prefixes" {
  description = "Comma-separated IP prefixes (e.g. '73.146.,10.0.') that should NOT trigger an alert"
  type        = string
  default     = ""
}

resource "aws_sns_topic" "admin_alerts" {
  name = "harpua2001-admin-alerts"
}

resource "aws_sns_topic_subscription" "admin_alerts_email" {
  topic_arn = aws_sns_topic.admin_alerts.arn
  protocol  = "email"
  endpoint  = var.admin_alert_email
}

# Grant Lambda permission to publish to the SNS topic
resource "aws_iam_role_policy" "lambda_sns_publish" {
  name = "lambda-sns-publish"
  role = aws_iam_role.lambda_exec.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["sns:Publish"]
      Resource = aws_sns_topic.admin_alerts.arn
    }]
  })
}

# ---------------------------------------------------------------------------
# Package Lambda
# ---------------------------------------------------------------------------
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/.build/lambda_src"
  output_path = "${path.module}/.build/ebay_notifications.zip"
  depends_on  = [null_resource.stage_lambda_src]
}

# Stage agent modules + lambda_function.py into .build/lambda_src before zip.
# Re-runs whenever any of the source files change.
resource "null_resource" "stage_lambda_src" {
  triggers = {
    lambda_function   = filesha256("${path.module}/lambda_function.py")
    seller_hub        = filesha256("${path.module}/../seller_hub_agent.py")
    seller_hub_phase2 = filesha256("${path.module}/../seller_hub_phase2.py")
    promoted_listings = filesha256("${path.module}/../promoted_listings_agent.py")
    best_offer        = filesha256("${path.module}/../best_offer_agent.py")
    promote_module    = filesha256("${path.module}/../promote.py")
  }
  provisioner "local-exec" {
    command = <<-EOT
      set -e
      mkdir -p ${path.module}/.build/lambda_src
      # Wipe stale stage
      rm -rf ${path.module}/.build/lambda_src/*
      # Copy Lambda entrypoint + every Python module Lambda routes import
      cp ${path.module}/lambda_function.py        ${path.module}/.build/lambda_src/
      cp ${path.module}/../seller_hub_agent.py    ${path.module}/.build/lambda_src/
      cp ${path.module}/../seller_hub_phase2.py   ${path.module}/.build/lambda_src/
      cp ${path.module}/../promoted_listings_agent.py ${path.module}/.build/lambda_src/
      cp ${path.module}/../best_offer_agent.py    ${path.module}/.build/lambda_src/
      cp ${path.module}/../promote.py             ${path.module}/.build/lambda_src/
      # promote.py imports a bunch of optional pricing modules — touch empty
      # shims so import doesn't fail in the Lambda runtime.
      for f in card_price_agent.py photo_audit_agent.py specifics_agent.py; do
        [ -f ${path.module}/../$f ] && cp ${path.module}/../$f ${path.module}/.build/lambda_src/ || true
      done
      # Lambda's Python runtime doesn't ship `requests`. Vendor it so the
      # agent modules (which all use requests for eBay REST calls) work.
      pip3 install --quiet --target ${path.module}/.build/lambda_src requests || \
        echo "  WARN: pip3 install requests failed — Lambda routes that need it will 503"
    EOT
  }
}

# ---------------------------------------------------------------------------
# IAM Role for Lambda
# ---------------------------------------------------------------------------
resource "aws_iam_role" "lambda_exec" {
  name = "ebay-notifications-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic_logs" {
  role       = aws_iam_role.lambda_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# ---------------------------------------------------------------------------
# Lambda Function
# ---------------------------------------------------------------------------
resource "aws_lambda_function" "ebay_notifications" {
  function_name    = "ebay-account-deletion-notifications"
  description      = "eBay marketplace account deletion notifications — GDPR/CCPA compliance"
  role             = aws_iam_role.lambda_exec.arn
  handler          = "lambda_function.lambda_handler"
  runtime          = "python3.12"
  filename         = data.archive_file.lambda_zip.output_path
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  timeout          = 10
  memory_size      = 128

  environment {
    variables = {
      EBAY_VERIFICATION_TOKEN = var.ebay_verification_token
      EBAY_ENDPOINT_URL       = var.ebay_endpoint_url != "" ? var.ebay_endpoint_url : "PENDING_SECOND_APPLY"
      EBAY_CLIENT_ID          = var.ebay_client_id
      EBAY_CLIENT_SECRET      = var.ebay_client_secret
      EBAY_REFRESH_TOKEN      = var.ebay_refresh_token
      EBAY_DEV_ID             = var.ebay_dev_id
      EBAY_RU_NAME            = var.ebay_ru_name
      REDDIT_CLIENT_ID        = var.reddit_client_id
      REDDIT_CLIENT_SECRET    = var.reddit_client_secret
      REDDIT_REFRESH_TOKEN    = var.reddit_refresh_token
      REDDIT_USER_AGENT       = var.reddit_user_agent
      FIVETRAN_API_KEY        = var.fivetran_api_key
      FIVETRAN_API_SECRET     = var.fivetran_api_secret
      FIVETRAN_CONNECTOR_ID   = var.fivetran_connector_id
      ADMIN_ALERT_SNS_TOPIC   = aws_sns_topic.admin_alerts.arn
      ADMIN_KNOWN_DEVICES     = var.admin_known_devices
      ADMIN_KNOWN_IP_PREFIXES = var.admin_known_ip_prefixes
    }
  }
}

# ---------------------------------------------------------------------------
# API Gateway v2 (HTTP API)
# ---------------------------------------------------------------------------
resource "aws_apigatewayv2_api" "ebay_notifications" {
  name          = "ebay-notifications-api"
  protocol_type = "HTTP"
  description   = "Public HTTPS endpoint for eBay marketplace account deletion notifications"
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.ebay_notifications.id
  name        = "$default"
  auto_deploy = true
}

resource "aws_apigatewayv2_integration" "lambda" {
  api_id                 = aws_apigatewayv2_api.ebay_notifications.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.ebay_notifications.invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "get" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "GET /ebay/notifications"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "post" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "POST /ebay/notifications"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "oauth_callback" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "GET /ebay/oauth/callback"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "health" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "GET /health"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "revise_post" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "POST /ebay/revise"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "revise_options" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "OPTIONS /ebay/revise"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "reddit_post_post" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "POST /ebay/reddit-post"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "reddit_post_options" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "OPTIONS /ebay/reddit-post"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "admin_login_post" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "POST /ebay/admin-login"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "admin_login_options" {
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "OPTIONS /ebay/admin-login"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

# ---------------------------------------------------------------------------
# Wave 7-10 routes — all the new agent endpoints. Each route is a POST +
# OPTIONS (CORS preflight). All target the same Lambda integration.
# ---------------------------------------------------------------------------
locals {
  agent_routes = [
    "preview-store-categories",
    "sync-store-categories",
    "promotion-rollup",
    "sync-promoted",
    "best-offer-bulk",
    "create-listing",
    "ai-chat",
    "upload-photos",
  ]
}

resource "aws_apigatewayv2_route" "agent_post" {
  for_each  = toset(local.agent_routes)
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "POST /ebay/${each.value}"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

resource "aws_apigatewayv2_route" "agent_options" {
  for_each  = toset(local.agent_routes)
  api_id    = aws_apigatewayv2_api.ebay_notifications.id
  route_key = "OPTIONS /ebay/${each.value}"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}

# ---------------------------------------------------------------------------
# Grant API Gateway permission to invoke Lambda
# ---------------------------------------------------------------------------
resource "aws_lambda_permission" "apigw" {
  statement_id  = "AllowAPIGatewayInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.ebay_notifications.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.ebay_notifications.execution_arn}/*/*"
}

# ---------------------------------------------------------------------------
# CloudWatch Log Group
# ---------------------------------------------------------------------------
resource "aws_cloudwatch_log_group" "lambda_logs" {
  name              = "/aws/lambda/${aws_lambda_function.ebay_notifications.function_name}"
  retention_in_days = 30
}

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
output "endpoint_url" {
  description = "Register this URL in eBay Developer Portal"
  # invoke_url for $default stage has no trailing slash — path starts with /
  value = "${aws_apigatewayv2_api.ebay_notifications.api_endpoint}/ebay/notifications"
}

output "lambda_function_name" {
  value = aws_lambda_function.ebay_notifications.function_name
}

output "api_gateway_id" {
  value = aws_apigatewayv2_api.ebay_notifications.id
}
